#
# IMPORTANT NOTE
#
# This chart inherits from our common library chart. You can check the default values/options here:
# https://github.com/k8s-at-home/library-charts/tree/main/charts/stable/common/values.yaml
#

image:
  # -- image repository
  repository: ghcr.io/sct/overseerr
  # -- image tag
  tag: "latest"
  # -- image pull policy
  pullPolicy: Always

resources:
  requests:
    cpu: 100m
    memory: 256Mi
  limits:
    cpu: 500m
    memory: 512Mi

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-worker3
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - plex-media-server
        namespaces:
        - plex
        topologyKey: kubernetes.io/hostname
      weight: 80

# -- environment variables.
# @default -- See below
env:
  # -- Set the container timezone
  TZ: UTC
  # -- Set the application log level
  LOG_LEVEL: info

# -- Configures service settings for the chart.
# @default -- See values.yaml
service:
  main:
    ports:
      http:
        port: 5055

ingress:
  # -- Enable and configure ingress settings for the chart under this key.
  # @default -- See values.yaml
  main:
    enabled: true
    ingressClassName: nginx
    annotations:
      cert-manager.io/cluster-issuer: letsencrypt-prod
      nginx.ingress.kubernetes.io/backend-protocol: HTTP
    hosts:
    - host: overseerr.homelab.example.com
      paths:
      - path: /
        pathType: Prefix
    tls:
    - hosts:
      - overseerr.homelab.example.com
      secretName: overseerr-tls

# -- Configure persistence settings for the chart under this key.
# @default -- See values.yaml
persistence:
  config:
    enabled: true
    existingClaim: overseerr-config
    mountPath: /app/config
