image:
  registry: ghcr.io
  repository: seerr-team/seerr
  pullPolicy: IfNotPresent
  tag: v3.3.0

extraEnv:
  - name: LOG_LEVEL
    value: info
  - name: TZ
    value: UTC

config:
  persistence:
    existingClaim: overseerr-config

ingress:
  enabled: true
  ingressClassName: traefik
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  hosts:
    - host: overseerr.lourenco.ch
      paths:
        - path: /
          pathType: Prefix
  tls:
    - hosts:
        - overseerr.lourenco.ch
      secretName: seerr-tls

resources:
  limits:
    cpu: 500m
    memory: 1536Mi
  requests:
    cpu: 100m
    memory: 768Mi

affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - preference:
          matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-worker3
        weight: 100
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - podAffinityTerm:
          labelSelector:
            matchExpressions:
              - key: app.kubernetes.io/name
                operator: In
                values:
                  - plex-media-server
          namespaces:
            - plex
          topologyKey: kubernetes.io/hostname
        weight: 80
