---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-paperless-export
spec:
  storageClassName: ""
  capacity:
    storage: 10Gi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.2
    path: "/mnt/user/paperless/export"
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
    - timeo=600
    - retrans=2
    - noresvport
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-paperless-export
  namespace: paperless
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 10Gi
  volumeName: nfs-paperless-export
