# Longhorn Custom Values
# For full values reference, see: https://github.com/longhorn/charts/blob/master/charts/longhorn/values.yaml

# Storage class configuration
persistence:
  reclaimPolicy: Retain
  defaultDataLocality: "disabled"

defaultBackupStore:
  backupTarget: s3://longhorn@ch-fr-1/
  backupTargetCredentialSecret: minio-bucket-credentials

# Ingress configuration for Longhorn UI
ingress:
  enabled: true
  host: longhorn.k3s.home
  ingressClassName: traefik
  tls: false
