---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-nextcloud-ro
spec:
  storageClassName: ""
  capacity:
    storage: 1Mi
  accessModes:
    - ReadOnlyMany
  nfs:
    server: 10.0.0.2
    path: "/mnt/user/nextcloud"
  mountOptions:
    - nfsvers=4.2
    - hard
    - noatime
    - timeo=600
    - retrans=2
    - noresvport
    - ro
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-nextcloud-ro
  namespace: immich
spec:
  accessModes:
    - ReadOnlyMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: nfs-nextcloud-ro
