---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-immich
spec:
  storageClassName: ""
  capacity:
    storage: 1Mi
  accessModes:
    - ReadWriteMany
  nfs:
    server: 10.0.0.2
    path: "/mnt/user/immich"
  mountOptions:
    - nfsvers=4.2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-immich
  namespace: immich
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: ""
  resources:
    requests:
      storage: 1Mi
  volumeName: nfs-immich
