---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: nfs-anime-plex
  labels:
    content: nfs-anime-plex
spec:
  storageClassName: nfs-static
  persistentVolumeReclaimPolicy: Retain
  capacity:
    storage: 8Ti
  accessModes:
    - ReadWriteMany
  volumeMode: Filesystem
  nfs:
    server: 10.0.0.7
    path: "/anime"
  mountOptions:
    - nfsvers=4.1
    - hard
    - noatime
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: nfs-anime-plex
  namespace: plex
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-static
  resources:
    requests:
      storage: 8Ti
  volumeName: nfs-anime-plex
