-- apartments DB schema — source of truth for the appart-bulle listing store.
-- Database `apartments` lives in the n8n-db CNPG cluster (see apartments-database.yaml).
-- Applied manually with psql; kept here so the schema is version-controlled and
-- reproducible on a fresh cluster. Idempotent (IF NOT EXISTS / ADD COLUMN IF NOT EXISTS).
--
--   kubectl exec -i -n n8n n8n-db-1 -c postgres -- \
--     psql -U postgres -d apartments < productivity/n8n/apartments-schema.sql

-- ---------------------------------------------------------------------------
-- listings: one row per apartment listing, keyed (source, source_id).
-- Enrichment columns (agency*, lat/lng, partner) are backfilled by APPT 21 for
-- e-mail-sourced listings via the tls-fetch service; see tls-fetch/README.md.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS listings (
    id           bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    source       text NOT NULL,
    source_id    text NOT NULL,
    url          text,
    title        text,
    rent_net     numeric,
    rent_gross   numeric,
    charges      numeric,
    rooms        numeric,
    m2           numeric,
    commune      text,
    address_raw  text,
    year_built   integer,
    floor        text,
    features     jsonb DEFAULT '[]'::jsonb,
    description  text,
    images       jsonb DEFAULT '[]'::jsonb,
    cross_key    text,
    triage       jsonb,
    fit_score    integer,
    status       text DEFAULT 'new',
    published_at timestamptz,
    first_seen   timestamptz NOT NULL DEFAULT now(),
    last_seen    timestamptz NOT NULL DEFAULT now(),
    notified_at  timestamptz,
    -- enrichment (APPT 21 / tls-fetch)
    agency         text,
    agency_contact text,
    lat            numeric,
    lng            numeric,
    partner        text,
    -- cross-portal dedup (APPT 20): cross_key is a coarse per-apartment fingerprint
    -- (commune|rooms|street-token-n<number>); a listing that duplicates an already-notified
    -- one from a DIFFERENT source (within a rent tolerance) is marked status='dup' + dup_of,
    -- its data merged into the canonical row, and no second notification is sent.
    dup_of         bigint,
    sources        text[] DEFAULT '{}',
    UNIQUE (source, source_id)
);
CREATE INDEX IF NOT EXISTS listings_cross_key_idx  ON listings (cross_key);
CREATE INDEX IF NOT EXISTS listings_first_seen_idx ON listings (first_seen);

-- ---------------------------------------------------------------------------
-- agency_reputation: user-curated verdict on a régie/agency. The agency NAME is
-- extracted automatically during enrichment (Comparis VendorInformation.Name);
-- only the good/neutral/bad verdict + note are hand-maintained. APPT 21 joins on
-- lower(name) and feeds the result into the LLM triage + notifications.
--   e.g. UPDATE agency_reputation SET reputation='bad',
--          note='délais de réponse, caution abusive' WHERE name='<régie>';
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS agency_reputation (
    name       text PRIMARY KEY,
    reputation text NOT NULL DEFAULT 'neutral'
               CHECK (reputation IN ('good', 'neutral', 'bad')),
    note       text,
    updated_at timestamptz NOT NULL DEFAULT now()
);
CREATE INDEX IF NOT EXISTS agency_reputation_lname ON agency_reputation (lower(name));

-- ---------------------------------------------------------------------------
-- portal_cookies: solved DataDome session tokens for portals whose live pages
-- curl_cffi can't clear on its own (immoscout24, homegate — the SMG pool). The
-- `datadome` token is captured once from a real browser on the home network and
-- ROLLS: APPT 21 sends the current token to the tls-fetch sidecar, and on every
-- 200 writes back the refreshed token the sidecar returns (keeping the session
-- alive).
--
-- CIRCUIT BREAKER (protects home-IP reputation — DataDome reputation is ~25-30%
-- of its trust score and is scored cross-customer/globally, so 403-hammering here
-- also degrades homegate/comparis). The `status` column IS the breaker:
--   * enrichment only fires when status='active' — an expired token therefore
--     generates ZERO further requests (no attempt is made at all);
--   * a 403 flips status='expired' immediately and is NEVER retried (retrying a
--     403 just gets the IP blocked harder — non-retryable by design);
--   * expiry is detected from ORGANIC enrich traffic (no standalone high-frequency
--     liveness probe, which would itself emit repeated 403s). A fresh token, pasted
--     by the user, resets status='active' and resumes traffic.
-- NEVER commit real token values — rows are populated/rotated at runtime only.
-- See tls-fetch/README.md.
-- ---------------------------------------------------------------------------
CREATE TABLE IF NOT EXISTS portal_cookies (
    portal       text PRIMARY KEY,          -- 'immoscout24' | 'homegate'
    datadome     text NOT NULL,             -- current solved/rolled token value
    user_agent   text NOT NULL,             -- exact browser UA the token is bound to
    status       text NOT NULL DEFAULT 'active'
                 CHECK (status IN ('active', 'expired')),
    last_ok      timestamptz,               -- last request that returned 200
    last_checked timestamptz,               -- last health-probe / use
    updated_at   timestamptz NOT NULL DEFAULT now()
);

-- The n8n app role (login user `apartments`) needs DML on these tables.
GRANT USAGE ON SCHEMA public TO apartments;
GRANT SELECT, INSERT, UPDATE, DELETE ON listings, agency_reputation, portal_cookies TO apartments;
GRANT USAGE, SELECT ON ALL SEQUENCES IN SCHEMA public TO apartments;
