apiVersion: postgresql.cnpg.io/v1
kind: Cluster
metadata:
  name: event-manager-postgres
  namespace: n8n
spec:
  affinity:
    podAntiAffinityType: preferred
  bootstrap:
    initdb:
      database: n8n_telegram_bot
      owner: n8n_user
      secret:
        name: event-manager-postgres-secret
  imageName: ghcr.io/cloudnative-pg/postgresql:17.5
  instances: 3
  monitoring:
    enablePodMonitor: true
  postgresql:
    parameters:
      shared_buffers: 128MB
  resources:
    limits:
      cpu: 500m
      memory: 512Mi
    requests:
      cpu: 250m
      memory: 256Mi
  storage:
    size: 8Gi
    storageClass: longhorn-single-replica
  backup:
    barmanObjectStore:
      destinationPath: "s3://event-manager-backups/"
      endpointURL: "http://10.0.0.7:8010"
      s3Credentials:
        accessKeyId:
          name: event-manager-s3-backup-credentials
          key: ACCESS_KEY_ID
        secretAccessKey:
          name: event-manager-s3-backup-credentials
          key: ACCESS_SECRET_KEY
      wal:
        compression: bzip2
      data:
        compression: bzip2
    retentionPolicy: "30d"
