image:
  repository: ghcr.io/alam00000/bentopdf-simple
  pullPolicy: IfNotPresent
  tag: v2.8.6

ingress:
  enabled: true
  className: traefik
  url: "bentopdf.k3s.home"

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 500m
    memory: 256Mi

livenessProbe:
  httpGet:
    path: /
readinessProbe:
  httpGet:
    path: /