image:
  repository: ghcr.io/alam00000/bentopdf-simple
  pullPolicy: Always
  tag: latest

ingress:
  enabled: true
  className: traefik
  url: "bentopdf.local"

resources:
  requests:
    cpu: 100m
    memory: 50Mi
  limits:
    cpu: 500m
    memory: 256Mi