---
apiVersion: postgresql.cnpg.io/v1
kind: ScheduledBackup
metadata:
  name: immich-scheduled-backup
  namespace: immich
spec:
  schedule: "0 4 0 ? * MON"
  backupOwnerReference: self
  cluster:
    name: immich-db
  immediate: true
