apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: qbit-media-config
  namespace: media
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn
  resources:
    requests:
      storage: 5Gi
