affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
      - weight: 100
        preference:
          matchExpressions:
            - key: kubernetes.io/hostname
              operator: In
              values:
                - k3s-worker4
  podAntiAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - podAffinityTerm:
        labelSelector:
          matchExpressions:
          - key: app.kubernetes.io/name
            operator: In
            values:
            - plex-media-server
        namespace: plex
        topologyKey: kubernetes.io/hostname
      weight: 90
env:
  PGID: 1000
  PRIVOXY_ENABLED: false
  PUID: 1000
  TZ: Etc/UTC
  UMASK: 2
  UNBOUND_ENABLED: false
  VPN_AUTO_PORT_FORWARD: true
  VPN_CONF: wg0
  VPN_FIREWALL_TYPE: auto
  VPN_HEALTHCHECK_ENABLED: false
  VPN_KEEP_LOCAL_DNS: false
  VPN_LAN_LEAK_ENABLED: false
  VPN_LAN_NETWORK: 192.168.1.0/24
  WEBUI_PORTS: 8080/tcp,8080/udp
image:
  pullPolicy: IfNotPresent
  repository: ghcr.io/hotio/qbittorrent
  tag: legacy-511863b
ingress:
  className: traefik
  enabled: true
  hosts:
  - host: torrent.local
    paths:
    - path: /
      pathType: ImplementationSpecific
  tls: []
persistence:
  config:
    enabled: true
    existingClaim: qbittorrent-config
  data:
    enabled: true
    existingClaim: nfs-torrent
replicaCount: 1
resources:
  limits:
    cpu: 1
    memory: 8Gi
  requests:
    cpu: 250m
    memory: 2Gi
service:
  port: 8080
  type: ClusterIP
vpn:
  pia:
    enabled: false
  wireguard:
    enabled: true
    proton: true
    existingSecret: "qbittorrent-vpn-config"
    secretKey: "wg0.conf"
    config: ""
