apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    email: CHANGE_ME_YOUR_EMAIL@example.com
    server: https://acme-v02.api.letsencrypt.org/directory
    privateKeySecretRef:
      name: letsencrypt-prod
    solvers:
    - dns01:
        route53:
          region: eu-central-1  # Change to your AWS region
          accessKeyID: CHANGE_ME_AWS_ACCESS_KEY_ID
          secretAccessKeySecretRef:
            name: route53-secret
            key: secret-access-key
