apiVersion: traefik.io/v1alpha1
kind: ServersTransport
metadata:
  name: long-timeout-600
  namespace: nextcloud
spec:
  forwardingTimeouts:
    responseHeaderTimeout: "600s"
    idleConnTimeout: "600s"
    dialTimeout: "30s"
