---
apiVersion: v1
kind: Secret
metadata:
  name: deltabadger-secrets
  namespace: deltabadger
type: Opaque
data:
  APP_ENCRYPTION_KEY: "CHANGE_ME" # openssl rand -hex 32, not needed in v1.6.26+
  DEVISE_SECRET_KEY: "CHANGE_ME" # openssl rand -hex 64, not needed in v1.6.26+
  SECRET_KEY_BASE: "dev-secret-key-not-for-production" # openssl rand -hex 64
