# jellyfin — chart: k8s-charts/jellyfin v0.2.4. Real deployed values (source of truth).
affinity:
  nodeAffinity:
    preferredDuringSchedulingIgnoredDuringExecution:
    - preference:
        matchExpressions:
        - key: kubernetes.io/hostname
          operator: In
          values:
          - k3s-worker1
      weight: 100
    requiredDuringSchedulingIgnoredDuringExecution:
      nodeSelectorTerms:
      - matchExpressions:
        - key: gpu.intel.com/device-id.0300-7d55.count
          operator: In
          values:
          - "1"
extraVolumeMounts:
- mountPath: /movies
  name: movies
- mountPath: /tv
  name: tv
- mountPath: /anime
  name: anime
- mountPath: /music
  name: music
extraVolumes:
- name: movies
  persistentVolumeClaim:
    claimName: nfs-movies
- name: tv
  persistentVolumeClaim:
    claimName: nfs-tv
- name: anime
  persistentVolumeClaim:
    claimName: nfs-anime
- name: music
  persistentVolumeClaim:
    claimName: nfs-music
image:
  pullPolicy: IfNotPresent
  tag: 10.11.6
ingress:
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
  enabled: false
  ingressClassName: traefik
  url: https://jellyfin.domain.com
persistence:
  cache:
    enabled: false
    existingClaim: ""
  config:
    enabled: true
    existingClaim: jellyfin-config
resources:
  limits:
    gpu.intel.com/i915: "1"
  requests:
    cpu: "1"
    gpu.intel.com/i915: "1"
    memory: 4Gi
service:
  port: 8096
  type: LoadBalancer
tolerations: []
