apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: gitea-redis
  namespace: gitea
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: longhorn-single-replica
  resources:
    requests:
      storage: 5Gi
